global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'remote_servers'
    static_configs:
      - targets:
        - 'localhost:8081'
        - 'localhost:8080'
