// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Log struct {
	LogID     int64     `json:"log_id"`
	TaskID    int64     `json:"task_id"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}

type Node struct {
	NodeID    int64     `json:"node_id"`
	Hostname  string    `json:"hostname"`
	IpAddr    string    `json:"ip_addr"`
	Status    int32     `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Task struct {
	TaskID          int64         `json:"task_id"`
	UserID          int64         `json:"user_id"`
	TaskName        string        `json:"task_name"`
	TaskDescription string        `json:"task_description"`
	Status          int32         `json:"status"`
	Priority        sql.NullInt32 `json:"priority"`
	Command         string        `json:"command"`
	CreatedAt       time.Time     `json:"created_at"`
}

type TaskNodeMapping struct {
	TnmID     int64     `json:"tnm_id"`
	TaskID    int64     `json:"task_id"`
	NodeID    int64     `json:"node_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	UserID    int32     `json:"user_id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
