CREATE TABLE "Tasks" (
  "task_id" BIGSERIAL PRIMARY KEY NOT NULL,
  "user_id" bigint NOT NULL,
  "task_name" varchar NOT NULL,
  "task_description" varchar NOT NULL,
  "status" int NOT NULL,
  "priority" int,
  "command" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "Nodes" (
  "node_id" BIGSERIAL PRIMARY KEY NOT NULL,
  "hostname" varchar NOT NULL,
  "ip_addr" varchar NOT NULL,
  "status" int NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "TaskNodeMapping" (
  "tnm_id" BIGSERIAL PRIMARY KEY NOT NULL,
  "task_id" bigint NOT NULL,
  "node_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "Logs" (
  "log_id" BIGSERIAL PRIMARY KEY NOT NULL,
  "task_id" bigint NOT NULL,
  "message" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "Users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar NOT NULL,
  "password" varchar NOT NULL,
  "api_key" varchar,
  "email" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

ALTER TABLE "Tasks" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "TaskNodeMapping" ADD FOREIGN KEY ("task_id") REFERENCES "Tasks" ("task_id");

ALTER TABLE "TaskNodeMapping" ADD FOREIGN KEY ("node_id") REFERENCES "Nodes" ("node_id");

ALTER TABLE "Logs" ADD FOREIGN KEY ("task_id") REFERENCES "Tasks" ("task_id");
